In [2]:
# Import libiraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

from statsmodels.tsa.statespace.sarimax import SARIMAX

from sklearn.metrics import mean_absolute_error, root_mean_squared_error, mean_absolute_percentage_error

In [5]:
### Project Workflow Get and frame. Load train.csv, pick one store, build a datetime index at daily
##frequency, and decide explicitly what to do with closed days

df = pd.read_csv("Rossman_store.csv")
df.head()

C:\Users\kazee\AppData\Local\Temp\ipykernel_41228\2898447697.py:4: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Rossman_store.csv")

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [6]:
#checking shape, info, and tail
df.shape

(1017209, 9)

In [7]:
df.info

<bound method DataFrame.info of          Store  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0            1          5  2015-07-31   5263        555     1      1
1            2          5  2015-07-31   6064        625     1      1
2            3          5  2015-07-31   8314        821     1      1
3            4          5  2015-07-31  13995       1498     1      1
4            5          5  2015-07-31   4822        559     1      1
...        ...        ...         ...    ...        ...   ...    ...
1017204   1111          2  2013-01-01      0          0     0      0
1017205   1112          2  2013-01-01      0          0     0      0
1017206   1113          2  2013-01-01      0          0     0      0
1017207   1114          2  2013-01-01      0          0     0      0
1017208   1115          2  2013-01-01      0          0     0      0

        StateHoliday  SchoolHoliday
0                  0              1
1                  0              1
2                  0              1
3                  0              1
4                  0              1
...              ...            ...
1017204            a              1
1017205            a              1
1017206            a              1
1017207            a              1
1017208            a              1

[1017209 rows x 9 columns]>

In [8]:
df.tail()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [21]:
#Check and Convert the Date column from string ('str') to datetime
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d")
df.info()

str
<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  datetime64[us]
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: datetime64[us](1), int64(7), object(1)
memory usage: 69.8+ MB

In [9]:
# check for missing value, duplicate & gap
df.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [22]:
print(df["Date"].dtype)

datetime64[us]

In [25]:
print(df.index.duplicated().sum())

1016267

In [27]:
print(df.index.value_counts())

Date
2013-01-02    1115
2013-01-03    1115
2013-01-04    1115
2013-01-05    1115
2013-01-06    1115
              ...
2014-12-27     935
2014-12-28     935
2014-12-29     935
2014-12-30     935
2014-12-31     935
Name: count, Length: 942, dtype: int64